/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import { useRef, useState, useMemo } from 'react';
import { Float, useGLTF, useTexture } from '@react-three/drei';

const Cube = ({ ...props }) => {
  const { nodes } = useGLTF('/models/cube-compressed.glb'); // already compressed
  const texture = useTexture('/textures/cube.png');

  const cubeRef = useRef();
  const [hovered, setHovered] = useState(false);

  // Memoize geometry and material for performance
  const geometry = useMemo(() => nodes.Cube.geometry.clone(), [nodes.Cube.geometry]);
  const material = useMemo(() => nodes.Cube.material.clone(), [nodes.Cube.material]);

  useGSAP(() => {
    gsap
      .timeline({ repeat: -1, repeatDelay: 0.5 })
      .to(cubeRef.current.rotation, {
        y: hovered ? '+=2' : `+=${Math.PI * 2}`,
        x: hovered ? '+=2' : `-=${Math.PI * 2}`,
        duration: 2.5,
        stagger: { each: 0.15 },
      });
  });

  return (
    <Float floatIntensity={1.5}>
      <group
        position={[9, -4, 0]}
        rotation={[2.6, 0.8, -1.8]}
        scale={0.74}
        dispose={null}
        {...props}
      >
        <mesh
          ref={cubeRef}
          castShadow={true}
          receiveShadow={true}
          geometry={geometry}
          material={material}
          onPointerEnter={() => setHovered(true)}
          onPointerLeave={() => setHovered(false)}
        >
          <meshMatcapMaterial matcap={texture} toneMapped={false} />
        </mesh>
      </group>
    </Float>
  );
};

// Preload the GLTF for faster performance
useGLTF.preload('/models/cube-compressed.glb');

export default Cube;
